ScottyLabs/cmucourses

README.md, backend/README.md, frontend/README.md
Adds README.md containing instructions about deployment for both backend/frontend and some background information.
=> Add readme with description + deployment instructions

frontend/package-lock.json, frontend/package.json, frontend/src/app/courses.ts, frontend/src/app/fce.ts, frontend/src/app/store.ts, frontend/src/app/user.ts, frontend/src/app/userSchedules.ts, frontend/src/app/utils.tsx, frontend/src/components/BookmarkedList.tsx, frontend/src/components/Buttons.tsx, frontend/src/components/CourseDetail.tsx, frontend/src/components/CourseList.tsx, frontend/src/components/CourseSearch.tsx, frontend/src/components/CourseSearchList.tsx, frontend/src/components/Header.tsx, frontend/src/components/ScheduleData.tsx, frontend/src/components/ScheduleSearch.tsx, frontend/src/components/ScheduleSelector.tsx, frontend/src/components/SearchBar.tsx, frontend/src/components/Topbar.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/course/[courseID].tsx, frontend/src/pages/saved.tsx, frontend/src/pages/schedules.tsx, frontend/src/pages/schedules/shared.tsx, frontend/src/styles/globals.css
Allows users to create and share schedules.
=> Schedule Explorer

backend/.prettierrc, backend/package.json, backend/src/app.js, backend/src/controllers/courses.js, backend/src/controllers/fces.js, backend/src/controllers/user.js, backend/src/models/course.js, backend/src/models/fce.js, backend/src/models/professor.js, backend/src/util.js
=> Reformat backend, add format command to package.json

frontend/package-lock.json, frontend/package.json, frontend/src/app/cache.ts, frontend/src/app/fce.ts, frontend/src/app/types.ts, frontend/src/app/user.ts, frontend/src/app/utils.tsx, frontend/src/components/Aggregate.tsx, frontend/src/components/CourseCard.tsx, frontend/src/components/CourseList.tsx, frontend/src/components/FCEDetail.tsx, frontend/src/components/FCETable.tsx, frontend/src/components/InstructorDetail.tsx, frontend/src/components/InstructorFCEDetail.tsx, frontend/src/components/Link.tsx, frontend/src/components/LoginModal.tsx, frontend/src/components/Page.tsx, frontend/src/components/StarRating.tsx, frontend/src/pages/course/[courseID].tsx, frontend/src/pages/instructor/[name].tsx
- Creates a new path, `/instructor/[name]`, that displays FCEs from that instructor.
- Links to that page from the FCE tables.
Closes #32
=> Basic professor page skeleton

frontend/src/pages/search.tsx
Redirects `/search?q=[...]` to the home page with the search filled in.
Closes #34
=> Search based on URL query

frontend/package-lock.json, frontend/package.json, frontend/src/components/Aggregate.tsx, frontend/src/components/BookmarkButton.tsx, frontend/src/components/Buttons.tsx, frontend/src/components/CourseCard.tsx, frontend/src/components/CourseDetail.tsx, frontend/src/components/CourseSearchList.tsx, frontend/src/components/DarkModeButton.tsx, frontend/src/components/FCEDetail.tsx, frontend/src/components/FCETable.tsx, frontend/src/components/Filter.tsx, frontend/src/components/Header.tsx, frontend/src/components/InstructorDetail.tsx, frontend/src/components/LoginModal.tsx, frontend/src/components/Page.tsx, frontend/src/components/ScheduleData.tsx, frontend/src/components/ScheduleSearch.tsx, frontend/src/components/ScheduleSelector.tsx, frontend/src/components/Schedules.tsx, frontend/src/components/SearchBar.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/Sidebar.tsx, frontend/src/components/SmallButton.tsx, frontend/src/components/Topbar.tsx, frontend/src/pages/course/[courseID].tsx, frontend/src/pages/index.tsx, frontend/src/pages/saved.tsx, frontend/src/pages/schedules.tsx, frontend/tailwind.config.js
- Reduce reliance on box-shadow for separating layers for a cleaner look.
- Reduce border-radius of cards.
- Move navigation to the side, makes other features more discoverable.
=> Design tweaks

frontend/src/components/CourseCard.tsx, frontend/src/components/Header.tsx, frontend/src/components/SearchBar.tsx, frontend/src/components/Sidebar.tsx, frontend/src/pages/_document.tsx, frontend/src/pages/saved.tsx
- Minor changes for better responsivity
=> Responsive changes

frontend/src/components/LoginModal.tsx, frontend/src/pages/_document.tsx
Weird issues with Safari because Safari is trash and sent from hell to torment me.
=> Fix issues with mobile safari and dialog

.github/workflows/lint.yml, backend/.eslintrc.json, backend/package-lock.json, backend/package.json, backend/src/controllers/courses.js, backend/src/controllers/user.js
- Installs and configures ESLint
- Creates new actions in `lint.yml`
Closes #43
=> Add linting to backend

frontend/package-lock.json, frontend/package.json, frontend/src/components/BookmarkButton.tsx, frontend/src/components/DarkModeButton.tsx, frontend/src/components/Filter.tsx, frontend/src/components/Header.tsx, frontend/src/components/Pagination.tsx, frontend/src/components/ScheduleSearch.tsx, frontend/src/components/ScheduleSelector.tsx, frontend/src/components/SearchBar.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/Sidebar.tsx
Heroicons released new versions of their icons. This upgrades to use those instead.
Ran locally.
=> Migrate to Heroicons 2

frontend/src/components/ScheduleData.tsx, frontend/src/components/ScheduleSearch.tsx
CSS changes for better responsiveness of Schedule Explorer page.
Closes #46 
Tested on smaller screen
=> Fix schedule explorer on mobile

README.md, frontend/src/components/Header.tsx, frontend/src/components/LoginModal.tsx, frontend/src/components/ScheduleSearch.tsx, frontend/src/pages/_app.tsx
Quick bug fix of schedules having wrong scrolling behavior.
=> Fix schedules

frontend/src/components/Link.tsx, frontend/src/components/Page.tsx, frontend/src/components/SideNav.tsx, frontend/src/components/Sidebar.tsx
Adds footer including information about ScottyLabs. More stuff to be added in the future, such as moving the feedback form down here and adding release notes/version numbers.
Ran locally.
=> Adds a barebones footer

frontend/.gitignore, frontend/next.config.js
Supports `.env` file in `frontend` folder for quick setup. Used for bootcamp.
Tested with local `.env` file.
=> Set up for bootcamp

frontend/src/app/userSchedules.ts, frontend/src/components/Toast.tsx, frontend/src/pages/schedules/shared.tsx, frontend/tailwind.config.js
Closes #72 
Tested locally, tried a shared link, tried deleting schedules.
=> Fix Shared Schedules

backend/src/controllers/courses.js, frontend/src/app/api/course.ts
Closes #80 
Tested locally using backend and frontend.
- OS:
- Browser:
=> Fix semesters not showing on search

frontend/src/pages/_app.tsx
Add description and keyword meta tags to head.
Ran locally and checked meta tags rendered.
=> Adds description and keyword meta tags

frontend/package-lock.json, frontend/package.json, frontend/src/app/filters.ts, frontend/src/app/store.ts, frontend/src/components/Aggregate.tsx, frontend/src/components/CourseSearchList.tsx, frontend/src/components/Filter.tsx, frontend/src/pages/_app.tsx
Deletes the "Show Exact ID" button and removes it from the queries.
Closes #90 
Tested locally
=> Delete Show by Exact ID

frontend/src/components/ScheduleSearch.tsx, frontend/src/components/filters/DepartmentFilter.tsx, frontend/src/components/filters/LevelFilter.tsx, frontend/tsconfig.json
Change colors for levels filter.
=> Change colors

package.json
This is to add commands so that Railway doesn't crash upon trying to build it.
=> add new package.json commands for Railway to use

package.json
follow up to #112 , forgot to add command to generate Prisma bindings
=> Add command to build prisma too

frontend/src/components/filters/SemestersOfferedFilter.tsx, package-lock.json
As title. Probably should figure out a way to automate this - perhaps by augmenting the scraper.
Closes #115
=> Adds S24 to offered in drop down filter

README.md
=> Update README.md with new installation instructions

backend/src/app.ts, package.json
Allows us to debug backend server errors better.
=> Expose backend server errors to deploy logs

backend/src/controllers/courses.mts, db/schema.prisma, package.json
Fix bad searches -- rewrite the getFilteredCourses method
=> Fix bad search

db/schema.prisma
fixes the problem that schedules are not shown
- OS:
- Browser:
=> fix errors in prisma schema causing schedules not to be shown

frontend/src/components/filters/SemestersOfferedFilter.tsx
- Desktop/Mobile: MacBook M2
- OS: MacOS Sonoma
=> adds f24 to offered in filter

frontend/src/app/user.ts, frontend/src/components/CourseCard.tsx, frontend/src/components/CourseSearchList.tsx, frontend/src/components/SchedulesCard.tsx, frontend/src/components/SchedulesDetail.tsx, frontend/src/components/SearchBar.tsx
- Desktop/Mobile: M2 MacBook Air
=> Course Schedule Improvements

frontend/src/components/filters/SemestersOfferedFilter.tsx
- Desktop/Mobile: MacBook Air M2
=> Changed block to flex

frontend/src/app/fce.ts
=> Fix typescript error

apps/frontend/src/components/Header.tsx, apps/frontend/src/components/Page.tsx
=> Add nova ad banner to CMU Courses

apps/frontend/package.json, apps/frontend/src/components/Header.tsx
=> Sizing bugfix

apps/frontend/src/components/SchedulesDetail.tsx
- OS:
- Browser:
- OS:
- Browser:
=> Added linking to maps in Schedule Details

apps/frontend/src/components/SchedulesDetail.tsx
=> Adding cmumaps linking

apps/frontend/src/components/filters/SemestersOfferedFilter.tsx
Add Spring 2025 to filter.
No testing :upside_down_face:
=> Add Spring 2025 to filter

apps/frontend/src/components/Header.tsx
=> Change NOVA to THX

apps/frontend/src/app/fce.ts
- Fixed FCE data by changing the formula of calculating workload, teaching rate, and course rate. 
- Changed File: `apps/frontend/src/app/fce.ts`
=> Fixed weighting of fce data

nixpacks.toml
* hotfix: attempt to fix railway deploy crashes with prisma
* hotfix: try creating nixPkgs
- OS:
- Browser:
=> Hotfix/prisma railway failure (#197)

apps/frontend/src/components/BookmarkButton.tsx, apps/frontend/src/components/GetTooltip.tsx
Fixed tooltip border by adding dark: class and added course button color on dark mode with dark mode tailwind CSS class.
Closes #207
checked and confirmed the changes on the frontend course cards.
- Browser:
=> Fixed tooltip border and added course button color on dark mode

README.md
=> Remove link to private scraper repository

apps/frontend/src/components/GenedsViewer.tsx
=> Added Dark Mode Stylization for Gened Viewer

apps/frontend/src/components/filters/DepartmentFilter.tsx
Closes #211 
Manually tested in http://127.0.0.1:3010/
=> Fix: Clear query value automatically in DepartmentFilter

package.json
=> fix: update incorrect bun version

apps/frontend/src/components/GenedsViewer.tsx, apps/frontend/src/components/Topbar.tsx
=> Fixed star layer bug

apps/frontend/src/components/GenedsViewer.tsx
=> fix: update disclaimer

apps/frontend/src/components/SearchBar.tsx
Improved dark mode contrast for search bar and results text
what theo wanted
=> Fix: Improve dark mode contrast

apps/frontend/src/components/filters/SemestersOfferedFilter.tsx
add fall 2025
i referenced how xavier added summer 2025
i checked that culinary mechanics doesnt show up when the filter is checked :(
=> add fall 2025 semester session filter

apps/frontend/src/app/utils.tsx, apps/frontend/src/components/CourseCard.tsx
=> fix: var -> variable for units name, fix bug when no fces show
