README.md, frontend/src/components/Header.tsx, frontend/src/components/LoginModal.tsx, frontend/src/pages/_app.tsx
Now that `cmucourses.com` points to this version of the Course Tool, it's time to remove the beta sign and rename this to CMU Courses.
Ran locally.
=> Rename Course Tool to CMU Courses, remove beta

frontend/src/components/CourseList.tsx, frontend/src/pages/schedules.tsx
Adds loading indicators in the following cases:
* In the schedule, when there are courses to search for but not all has been found.
* In the schedule, when there are courses to search for but none has been found yet.
The loading indicator in the course explorer was already added prior to this PR.
Closes #56 
- Node.js version: v18.9.0
- Desktop/Mobile: Linux
- Browser: Firefox v104.0.2
=> Add loading indicators

frontend/src/components/ScheduleSearch.tsx
Now hyphenates parts of a all-numeric course code (e.g. 152 -> 15-2, 1521 -> 15-21, 15213 -> 15-213).
Closes #74
Replaces GH-78.
=> Simplified implementation of omitted hyphen

frontend/src/components/ScheduleSearch.tsx
15150 matches but 15-150 doesn't, because 15-150 -> 15-15-0
This should fix it.
=> Hotfix for ScheduleSearch not matching full course ID

frontend/src/components/Filter.tsx
When a department is chosen from the dropdown, the department checkbox is set to true. Similarly, when the unit range selector is changed, the unit checkbox is set to true.
Non-breaking change.
Closes #47
=> Activate the department & unit filters on interaction

frontend/src/components/Aggregate.tsx, frontend/src/components/ScheduleData.tsx
Should fix #76.
This allows backspacing to work as a user might expect; i.e. they can clear the field and enter a new value. If the user leaves the field blank and unfocuses the field, it will revert back to its last valid value.
This was more complicated to implement than expected. An auxiliary state has to be implemented to handle the case when the field is temporarily blank (a future developer may be able to address this). This auxiliary state updates the global state (i.e. calls the dispatch function) through a useEffect hook.
In addition, due to the limitations of the input[type=number] element, we need to add a onKeyPress handler to disable key presses for non-numeric keys, as the onChange handler cannot detect when non-numeric input is given to the field.
Closes #76 
**Test …
=> Allow "Semesters to Show" field to be temporarily blank

frontend/src/components/ScheduleSearch.tsx
Adds a `flex-wrap` property to the search so that the search bar spills to the next line instead of going off the page.
Closes #94 
Tested locally, added a bunch of courses to see if the search bar goes off.
=> Fix schedule search

package.json
We need the tsc compiler to build and serve
Fixes failing builds
need to check deployment status
=> Move typescript from devDependencies to dependencies

backend/nodemon.json
Quick fix for .ts error when starting the backend:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ...
=> Update nodemon.json to fix .ts error

backend/src/controllers/courses.mts
- Add check for if prisma search result is empty to prevent destructuring of undefined object
Closes: N/A
=> Minor backend bug fix: "Unhandled Runtime Error" for all search queries that return no results

backend/nodemon.json, package-lock.json, package.json
Quick upgrade to Prisma Client from its 4.12 to 5.6. Addresses the bug where the unit count filter was broken. 
May need to regenerate database with "npm run db-generate".
Closes #124 
- OS:
- Browser:
=> Upgrade Prisma Client to 5.6 - Resolves Unit Filter Bug

frontend/src/app/filters.ts, frontend/src/components/filters/DepartmentFilter.tsx
Added text input to filter department search for ease of use. Met a number of technical and styling challenges, but I believe this is the best that can be done for now.
Backspace deletes filters, tab autofills the first option if in input mode.
Closes #133 
- Node.js version: v18.18.0
- Desktop: MacBook Air M2
- OS: MacOS Sonoma
=> Department filter search

backend/src/controllers/courses.mts
Fixed backend for schedules that only pulls certain data when getting course data in the schedules page.
- Desktop/Mobile: MacBook Air M2
=> Fixed backend for schedules

frontend/src/app/fce.ts, frontend/src/app/utils.tsx, frontend/src/components/FCETable.tsx
Some courses have 0 fce responses which skews the average calculation because each metric defaults to zero.
Tested the fce screen on the following courses:
- Desktop/Mobile: Macbook Air M2
=> Fixed issue of having 0 fce responses for certain instructors

frontend/src/app/filters.ts, frontend/src/components/SearchBar.tsx
Put in button to reset filters
- Desktop/Mobile: Macbook Air M2
- OS: MacOS
=> Button to reset filters

frontend/src/app/cache.ts, frontend/src/app/fce.ts, frontend/src/app/types.ts, frontend/src/app/utils.tsx, frontend/src/components/ScheduleData.tsx, frontend/src/components/ScheduleSelector.tsx
- Desktop/Mobile: Macbook Air M2
=> Schedules Builder Improvements

frontend/src/app/utils.tsx
- Node.js version: 18
- Desktop/Mobile: Macbook Air M2
=> Add check that id exists in standardizeId

README.md
<Updated Readme for bun, replacing the npm setup guide.>
- OS:
- Browser:
=> readme update test1

README.md
Edited the readme file to reflect changes in the setup procedure for bun. Removed the frontend and backend sections since both setup can be completed by running bun. Changed the command lines to code block.
=> Edited the readme file to reflect changes in the setup procedure for bun.

apps/frontend/src/app/user.ts, apps/frontend/src/components/SearchBar.tsx
Added showAll option for the Search page as a tri-state checkbox, based on the show settings of FCEs, Course Info, and Schedules.
Trying out different combinations of show selections for FCEs, Course Info, and Schedules, for both logged-in users and guests.
- Node.js version: v20.16.0
- Desktop/Mobile: Desktop
- OS: Windows
- Browser: Chrome
=> Added showAll option for the Search page as a tri-state checkbox

apps/frontend/src/components/StarRating.tsx
Fixed the fill colors of rating stars; related to [commit d23e09d](https://github.com/ScottyLabs/cmucourses/commit/d23e09d4a60a14a7521a811ddf341e9133c93c7f#diff-2e458e59a22a5b335c48e0381859fea97ea63aecdc3247142f37e3b1bd29651fL21).
Checking color changes on frontend.
Node.js version: v20.16.0
Desktop/Mobile: Desktop
OS: Windows
Browser: Chrome
=> Fix StarRating colors

apps/frontend/src/components/GenedsViewer.tsx
=> added placeholder to gened search bar

apps/backend/src/app.ts, apps/backend/src/controllers/courses.ts, apps/backend/src/util.ts, apps/frontend/src/app/types.ts, apps/frontend/src/components/CourseDetail.tsx, apps/frontend/src/components/PostReqCourses.tsx, apps/frontend/src/components/PreReqCourses.tsx, apps/frontend/src/components/ReqTreeCard.tsx, apps/frontend/src/components/ReqTreeDetail.tsx
=> Course Tree for Staging Deployment

apps/backend/src/app.ts, apps/backend/src/controllers/courses.ts, apps/backend/src/util.ts, apps/frontend/src/app/api/course.ts, apps/frontend/src/app/types.ts, apps/frontend/src/components/Buttons.tsx, apps/frontend/src/components/CourseDetail.tsx, apps/frontend/src/components/PostReqCourses.tsx, apps/frontend/src/components/PreReqCourses.tsx, apps/frontend/src/components/ReqTreeCard.tsx, apps/frontend/src/components/ReqTreeDetail.tsx
This pull request adds the requisite tree feature, which shows a tree of pre-requisites and post-requisites of courses in the course detail page. The feature enhances the user experience by providing a clear and organized visual representation of course dependencies. 
Closes #53
This feature was tested mainly through manual testing since most parts of the implementation were about the visualization and rendering of the tree. Error handling techniques were used to ensure error-free code, as well as manual validation. Backend testing also took place, as we tested the outputs of new functions we implemented. 
- Node.js version: 22.7.0
- Desktop/Mobile: Desktop 
- Browser: Chrome
=> Add pre-/post-requisite tree under each class 
